# Generated by Django 2.0.6 on 2018-06-20 14:44

import django.contrib.auth.validators
from django.db import migrations, models
import social_django.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20180519_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=94, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='usersocialauth',
            name='extra_data',
            field=social_django.fields.JSONField(default=dict),
        ),
    ]
